name: Continuous Integration

on:
  push:
    branches:
    - 'main'
    paths-ignore:
    - '.github/workflows/**'
    - 'README.md'

jobs:
  build:

    runs-on: windows-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Entire history required by Nerdbank.GitVersioning
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: Publish package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }} --skip-duplicate
