name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Entire history required by Nerdbank.GitVersioning
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --filter 'TestCategory != Bug & TestCategory != MissingFeature' --verbosity normal
    - name: Pack
      run: dotnet pack --no-build
