name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Entire history required by Nerdbank.GitVersioning
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --no-build
