name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v5
      with:
        fetch-depth: 0 # Entire history required by Nerdbank.GitVersioning
    - name: Set up .NET
      uses: actions/setup-dotnet@v5
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --filter "TestCategory != Bug & TestCategory != FeatureRequest" --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-build
